version: '3'

services:
  redis:
    image: redis
    ports:
      - '6379:6379'
  mongo3:
    image: mongo:3
    ports:
      - '27017:27017'
  adminer:
    image: adminer
    ports:
      - '30080:8080'
  postgres14:
    image: postgres:14
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_USER=root'
      - 'POSTGRES_PASSWORD=root'
  mysql8:
    image: mysql:8
    ports:
      - '3306:3306'
    environment:
      - 'MYSQL_ROOT_PASSWORD=root'
  elasticsearch5:
    image: elasticsearch:5.6.8-alpine
    ports:
      - '30105:9200'
    environment:
      - 'ES_JAVA_OPTS=-Xms256m -Xmx256m'
    ulimits:
      nofile: 10240
    volumes:
      - './elasticsearch-plugins:/tmp/elasticsearch-plugins'
  elasticsearch7:
    image: elasticsearch:7.17.2
    ports:
      - '30107:9200'
    environment:
      - 'ES_JAVA_OPTS=-Xms256m -Xmx256m'
      - 'discovery.type=single-node'
    volumes:
      - './elasticsearch-plugins:/tmp/elasticsearch-plugins'
  elasticsearch8:
    image: elasticsearch:8.5.2
    ports:
      - '30108:9200'
    environment:
      - 'ES_JAVA_OPTS=-Xms256m -Xmx256m'
      - 'discovery.type=single-node'
      - 'xpack.security.enabled=false'
    volumes:
      - './elasticsearch-plugins:/tmp/elasticsearch-plugins'
