version: '3'

services:
  redis:
    image: redis
    ports:
      - '6379:6379'
  mongo3:
    image: mongo:3
    ports:
      - '27017:27017'
  mongo:
    image: mongo:latest
    ports:
      - '27018:27017'
  postgres15:
    image: postgres:15
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_USER=root'
      - 'POSTGRES_PASSWORD=root'
  elasticsearch5:
    image: elasticsearch:5.6.16-alpine
    ports:
      - '30105:9200'
    environment:
      - 'ES_JAVA_OPTS=-Xms256m -Xmx256m'
    ulimits:
      nofile: 10240
    volumes:
      - './elasticsearch-plugins:/tmp/elasticsearch-plugins'
  elasticsearch7:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    ports:
      - '30107:9200'
    environment:
      - 'ES_JAVA_OPTS=-Xms256m -Xmx256m'
      - 'discovery.type=single-node'
    volumes:
      - './elasticsearch-plugins:/tmp/elasticsearch-plugins'
