version: '3'

services:
  mongo3:
    image: mongo:3
    ports:
      - '27017:27017'
  elasticsearch5:
    image: elasticsearch:5.6.8-alpine
    ports:
      - '30105:9200'
    environment:
      - 'ES_JAVA_OPTS=-Xms256m -Xmx256m'
    volumes:
      - './elasticsearch-plugins:/tmp/elasticsearch-plugins'
  elasticsearch6:
    image: elasticsearch:6.8.16
    ports:
      - '30106:9200'
    environment:
      - 'ES_JAVA_OPTS=-Xms256m -Xmx256m'
      - 'discovery.type=single-node'
    volumes:
      - './elasticsearch-plugins:/tmp/elasticsearch-plugins'
