services:
  mongo3:
    image: mongo:3
    ports:
      - '27017:27017'
  elasticsearch5:
    image: elasticsearch:5.6.16
    ports:
      - '30105:9200'
    environment:
      - 'ES_JAVA_OPTS=-Xms256m -Xmx256m'
    volumes:
      - './install-elasticsearch-plugins-for-container.sh:/tmp/install-plugins.sh'
  elasticsearch6:
    image: elasticsearch:6.8.15
    ports:
      - '30106:9200'
    environment:
      - 'ES_JAVA_OPTS=-Xms256m -Xmx256m'
      - 'discovery.type=single-node'
    volumes:
      - './install-elasticsearch-plugins-for-container.sh:/tmp/install-plugins.sh'
  elasticsearch7:
    image: elasticsearch:7.14.0
    ports:
      - '30107:9200'
    environment:
      - 'ES_JAVA_OPTS=-Xms256m -Xmx256m'
      - 'discovery.type=single-node'
    volumes:
      - './install-elasticsearch-plugins-for-container.sh:/tmp/install-plugins.sh'
